package akka.persistence.inmem.snapshot

import akka.persistence.inmem.InMemoryPluginSupport
import akka.persistence.snapshot.SnapshotStoreSpec

class InMemorySnapshotStoreSpec extends SnapshotStoreSpec(InMemoryPluginSupport.config)