package com.productfoundry.akka.snapshot

import akka.persistence.snapshot.SnapshotStoreSpec
import com.productfoundry.akka.InMemoryPluginSupport

class InMemorySnapshotStoreSpec extends SnapshotStoreSpec(InMemoryPluginSupport.config)